"""update hobbycourses table

Revision ID: 6f4b3b3469ee
Revises: 856ef56a09b2
Create Date: 2024-12-11 03:08:47.622959

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f4b3b3469ee"
down_revision: Union[str, None] = "856ef56a09b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("Hobbycourses_id_hobby_fkey", "Hobbycourses", type_="foreignkey")
    op.create_foreign_key(
        None,
        "Hobbycourses",
        "Hobbies",
        ["id_hobby"],
        ["id"],
        ondelete="cascade",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Hobbycourses", type_="foreignkey")
    op.create_foreign_key(
        "Hobbycourses_id_hobby_fkey",
        "Hobbycourses",
        "Hobbies",
        ["id_hobby"],
        ["id"],
    )
    # ### end Alembic commands ###
