"""update tables

Revision ID: 75dbccda8fc6
Revises: 77da316c26a2
Create Date: 2024-12-10 18:32:41.031744

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75dbccda8fc6"
down_revision: Union[str, None] = "77da316c26a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "Userstype", ["name_type"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Userstype", type_="unique")
    # ### end Alembic commands ###
