"""update user table

Revision ID: 8c2d8d85c583
Revises: 6f4b3b3469ee
Create Date: 2024-12-11 12:55:47.833939

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c2d8d85c583"
down_revision: Union[str, None] = "6f4b3b3469ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "Portfolio", ["id_user"])
    op.add_column(
        "Users",
        sa.Column("user_surname", sa.String(length=125), nullable=False),
    )
    op.add_column("Users", sa.Column("date_birthday", sa.Date(), nullable=False))
    op.alter_column(
        "Users",
        "user_name",
        existing_type=sa.VARCHAR(length=85),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Users",
        "user_name",
        existing_type=sa.VARCHAR(length=85),
        nullable=True,
    )
    op.drop_column("Users", "date_birthday")
    op.drop_column("Users", "user_surname")
    op.drop_constraint(None, "Portfolio", type_="unique")
    # ### end Alembic commands ###
