"""update user table

Revision ID: c00401af4d6e
Revises: e203832b2c94
Create Date: 2024-12-10 19:51:05.689015

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c00401af4d6e"
down_revision: Union[str, None] = "e203832b2c94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Users", sa.Column("id_university", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "Users", "University", ["id_university"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Users", type_="foreignkey")
    op.drop_column("Users", "id_university")
    # ### end Alembic commands ###
