"""update user table

Revision ID: e203832b2c94
Revises: 75dbccda8fc6
Create Date: 2024-12-10 18:53:15.099868

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e203832b2c94"
down_revision: Union[str, None] = "75dbccda8fc6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Users",
        "user_name",
        existing_type=sa.VARCHAR(length=85),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Users",
        "user_name",
        existing_type=sa.VARCHAR(length=85),
        nullable=False,
    )
    # ### end Alembic commands ###
